### ISSUE TITLE
Crash on joining server

### ISSUE THREAD

**Issue by primetoxinz** [austinv11/PeripheralsPlusPlus#42]
http://paste.ee/p/YwEN9
this just randomly started happening, I would give more info but really have none

**Comment by austinv11** [comment]
Can you try installing this version https://drone.io/github.com/austinv11/PeripheralsPlusPlus/files and let me know if it fixes it?

**Comment by primetoxinz** [comment]
this issue may be bigger than just your mod. I have had galacticraft bosses spawning in the overworld. something must be screwing with the spawn list... will look into it

**Comment by austinv11** [comment]
The latest version of P++ fixes this. And I believe the problem is having too many mobs. If you have further issues, contact other mod devs saying that this can be avoided by mods not registering their entity with a global id, they should use this: https://github.com/MinecraftForge/FML/blob/master/src/main/java/net/minecraftforge/fml/common/registry/EntityRegistry.java#L146 instead.
